// smart-h5-vue2/src/views-mobile/pages/backLog/dorm-exit/detail.vue
<!--
- @name 退宿申请
-->

<template>
  <div class="page3-detail">
    <div class="-line-20 -line-background"></div>
    <div class="block">
      <div class="row name-info">
        <div class="name">{{ detailInfo.name }}</div>
        <div class="img">
          <tce-image :src="detailInfo.facePic ? detailInfo.facePic : holderPerson" :width="72" :height="72"></tce-image>
        </div>
      </div>
      <div class="row">
        <div class="label">
          <tce-label-justify label="房间信息:"></tce-label-justify>
        </div>
        <div class="value">
          <ul>
            <li class="roomLi" v-for="(_item, index) in detailInfo.dorDetailStr" :key="index">
              {{ _item }}
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="label">
          <tce-label-justify label="退宿原因:"></tce-label-justify>
        </div>
        <div class="value">{{ detailInfo.quitReasonDesc }}</div>
      </div>
      <div class="row">
        <div class="label">
          <tce-label-justify label="预计离开时间:"></tce-label-justify>
        </div>
        <div class="value">{{ detailInfo.applyLeaveTime }}</div>
      </div>
      <div class="row">
        <div class="label">
          <tce-label-justify label="备注:"></tce-label-justify>
        </div>
        <div class="value">{{ detailInfo.remark }}</div>
      </div>
      <div class="row">
        <div class="label">
          <tce-label-justify label="照片:"></tce-label-justify>
        </div>
        <div class="value imgList">
          <div class="img" v-if="detailInfo.imgs && detailInfo.imgs[0]">
            <tce-image :src="detailInfo.imgs[0]" :width="72" :height="72" :previewImage="true"></tce-image>
          </div>
          <div class="img" v-if="detailInfo.imgs && detailInfo.imgs[1]">
            <tce-image :src="detailInfo.imgs[1]" :width="72" :height="72" :previewImage="true"></tce-image>
          </div>
          <div class="img" v-if="detailInfo.imgs && detailInfo.imgs[2]">
            <tce-image :src="detailInfo.imgs[2]" :width="72" :height="72" :previewImage="true"></tce-image>
          </div>
        </div>
      </div>
    </div>
    <div class="-line-20 -line-background"></div>
    <div class="block">
      <div class="row">
        <div style="font-weight: 600">审批流程</div>
      </div>
      <process :list="detailInfo.processRecord"></process>
    </div>
    <div class="-line-20 -line-background" v-if="curTabIndex == 0"></div>
    <div class="block" style="padding-bottom: 20px" v-if="curTabIndex == 0">
      <div class="row">
        <div style="font-weight: 600">描述(非必填)</div>
      </div>
      <cube-textarea v-model="remark" :placeholder="placeholder" :maxlength="maxlength" :autofocus="autofocus"></cube-textarea>
    </div>
    <page3Bottom v-if="detailInfo.status === 1 && curTabIndex == 0">
      <div slot="inner" class="btn-inner">
        <button @click="dealHandle(3)" class="tce-button tce-button--primary is-plain">拒绝</button>
        <button @click="dealHandle(2)" class="tce-button tce-button--primary">通过</button>
      </div>
    </page3Bottom>
    <page3Bottom v-if="detailInfo.status === 2 && curTabIndex == 0">
      <div slot="inner" class="btn-inner">
        <button @click="dealHandle(5)" class="tce-button tce-button--primary is-plain">拒绝</button>
        <button @click="dealHandle(4)" class="tce-button tce-button--primary">保安通过</button>
      </div>
    </page3Bottom>
  </div>
</template>

<script>
import process from './components/process/index'
import { getDetail, getScanDetail } from '@/services/dormExit'
import { confirmDormExit } from '@/services/backLog'
// confirmDormExit
import { GET_IMAGE_URL } from '../../../../conf'
import holderPerson from './img/user.png'
import page3Bottom from '@/views-mobile/components/page3-bottom'
import store from '@/store'

export default {
  components: {
    process,
    page3Bottom
  },
  data() {
    return {
      baseInfo: {},
      holderPerson: holderPerson,
      detailInfo: {},
      remark: '',
      placeholder: '请输入内容',
      maxlength: 50,
      autofocus: true,
      curTabIndex: 1, // 是否展示审批按钮 1隐藏 0展示
      isScan: false // true 扫码进入 保安详情接口修改
    }
  },
  computed: {},
  props: {},
  watch: {},
  methods: {
    /**
     * 详情
     */
    async getDetail() {
      this.$loading.show()
      let res
      if (this.isScan) {
        res = await getScanDetail(this.$route.query.id)
        this.curTabIndex = 0
      } else {
        res = await getDetail(this.$route.query.id)
      }
      this.$loading.hide()
      if (res.code === 0 && res.data !== null) {
        this.detailInfo = res.data
        this.detailInfo['facePic'] = GET_IMAGE_URL + '/' + this.detailInfo['faceId']
        if (this.detailInfo.isApprove) {
          this.curTabIndex = 0
        }
      } else {
        this.$tceMobile.toast(res.message || '网络错误')
        this.$router.push({
          path: '/xuchang/home'
        })
      }
    },
    async dealHandle(s) {
      const obj = {
        id: this.detailInfo.id,
        remark: this.remark,
        status: s,
        approveBadge: this.baseInfo.employeeBadge
      }
      this.$loading.show()
      const res = await confirmDormExit(obj)
      this.$loading.hide()
      if (res.code === 0 && res.data) {
        if (this.isScan) {
          this.$router.push({
            path: '/xuchang/home'
          })
        } else {
          this.$router.push({
            path: '/xuchang/backLog/dormExit',
            query: {
              curTabIndex: 1
            }
          })
        }
      } else {
        this.$tceMobile.toast(res.message || '网络错误')
      }
    }
  },
  /**
   * 生命周期 created
   */
  created() {
    if (this.$route.query.isScan) {
      this.isScan = this.$route.query.isScan
    }
    this.baseInfo = store.getters.userInfoBase
    // this.curTabIndex = this.$route.query.curTabIndex

    this.getDetail()
  },
  /**
   * 生命周期 mounted
   */
  mounted() {},
  /**
   * 生命周期 beforeDestroy
   */
  beforeDestroy() {}
}
</script>

<style lang="scss" scoped>
.page3-detail {
  background: $TCE-Background-Grey;
  width: 100%;
  min-height: 100%;
  padding: rem(20) rem(20) rem(200) rem(20);
  .block {
    background: #fff;
    padding: 0 rem(30);
    .row {
      display: flex;
      border-bottom: 1px solid #eee;
      padding: rem(30) 0;
      .label {
        color: #999;
        width: rem(130);
        flex: none;
      }
      .value {
        flex: 1;
        padding-left: rem(30);
        text-align: right;
      }
    }
    & .row:last-child {
      border: none;
    }
  }
  .name-info {
    display: flex;
    align-items: center;
    justify-content: space-between;
    .name {
      font-size: 16px;
      font-weight: bold;
    }
    .img {
      width: rem(100);
      height: rem(100);
    }
  }
  .imgList {
    display: flex;
    .img {
      width: rem(120);
      height: rem(120);
      margin-right: rem(20);
    }
  }
  .block-code {
    padding: rem(70) 0 rem(50) 0;
    .codeImg {
      width: rem(500);
      height: rem(500);
      margin: 0 auto;
    }
    .tip {
      margin-top: rem(30);
      color: #999;
      text-align: center;
    }
  }
  .page3-bottom {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .btn-inner {
    width: 90%;
    border-radius: rem(50);
    background: #fff;
    margin-top: rem(10);
    display: flex;
    justify-content: center;
    align-items: center;
    button {
      margin: 0 rem(20);
    }
  }
}
</style>

// smart-h5/src/app/backlog/dorm-exit/detail/page.tsx
'use client'
import { useQuery } from '@tanstack/react-query'
import { ImageViewer, SpinLoading, TextArea, Toast } from 'antd-mobile'
import Image from 'next/image'
import { useRouter, useSearchParams } from 'next/navigation'
import { Suspense, useEffect, useRef, useState } from 'react'
import { ApprovalTimeline } from '@/components/approval-timeline'
import { FaceAvatar } from '@/components/face-avatar'
import { PageShell } from '@/components/page-shell'
import { useRequireAuth } from '@/features/auth/use-require-auth'
import { getEmployeeBaseInfo } from '@/features/employee/api'
import { updateExitStatus } from '@/features/backlog/api'
import { exitProcessNodes } from '@/features/backlog/exit-process'
import { getDormExitDetail } from '@/features/dorm-services/api'

function InfoRow({ label, value }: { label: string; value?: React.ReactNode }) {
  if (!value) return null
  return (
    <div className="flex justify-between gap-4 border-b border-border-soft py-2.5 last:border-b-0">
      <span className="flex-none text-[13px] text-mid">{label}</span>
      <span className="min-w-0 text-right text-[13px] font-medium break-all">{value}</span>
    </div>
  )
}

function DormExitApprovalDetailInner() {
  const authorized = useRequireAuth()
  const router = useRouter()
  const params = useSearchParams()
  const id = params.get('id') ?? ''
  const readOnly = params.get('tab') === 'done'
  const [remark, setRemark] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const baseInfo = useQuery({
    queryKey: ['employee', 'baseinfo'],
    queryFn: getEmployeeBaseInfo,
    enabled: authorized,
  })
  const badge = baseInfo.data?.code === 0 ? baseInfo.data.data?.employeeBadge : undefined

  const detail = useQuery({
    queryKey: ['exit-detail', id],
    queryFn: () => getDormExitDetail(id),
    enabled: authorized && id !== '',
  })
  const info = detail.data?.code === 0 ? detail.data.data : undefined
  const failed = id === '' || detail.isError || (detail.isSuccess && (detail.data.code !== 0 || !detail.data.data))

  const warnedRef = useRef(false)
  useEffect(() => {
    if (failed && !warnedRef.current) {
      warnedRef.current = true
      Toast.show(detail.data?.message || '网络错误')
      router.replace('/home')
    }
  }, [failed, detail.data?.message, router])

  // 审批模式 = isApprove === true 且非只读 Tab；isApprove 缺失/false 默认只读（旧版查看模式）。
  const approveMode = !readOnly && info?.isApprove === true
  const status = info?.status
  const photos = (info?.imgs ?? []).filter((img): img is string => !!img).slice(0, 3)

  async function submit(nextStatus: 2 | 3 | 4 | 5) {
    if (submitting) return
    if (!badge) return Toast.show('获取用户信息失败！')
    setSubmitting(true)
    try {
      const res = await updateExitStatus({ id, status: nextStatus, approveBadge: badge, remark })
      if (res.code === 0 && res.data) {
        router.replace('/backlog/dorm-exit?tab=done')
      } else {
        Toast.show(res.message || res.msg || '网络错误')
      }
    } catch (error) {
      Toast.show(error instanceof Error ? error.message : '网络错误')
    } finally {
      setSubmitting(false)
    }
  }

  if (!authorized) return null

  return (
    <PageShell title="退宿审批">
      {detail.isPending || failed || !info ? (
        <div className="flex justify-center py-16">
          <SpinLoading color="primary" />
        </div>
      ) : (
        <div className="flex flex-col gap-3 pb-24">
          {/* 申请人卡 */}
          <div className="rounded-2xl bg-white px-4 py-2 shadow-[0_16px_40px_rgba(89,87,87,0.10)]">
            <div className="flex items-center gap-3 border-b border-border-soft py-3">
              <FaceAvatar faceId={info.faceId} />
              <span className="text-[15px] font-bold">{info.name}</span>
            </div>
            <InfoRow
              label="房间信息"
              value={info.dorDetailStr?.map((line, i) => (
                <span key={i} className="block">
                  {line}
                </span>
              ))}
            />
            <InfoRow label="退宿原因" value={info.quitReasonDesc} />
            <InfoRow label="预计离开时间" value={info.applyLeaveTime} />
            <InfoRow label="备注" value={info.remark} />
            {photos.length > 0 && (
              <div className="flex gap-2.5 py-2.5">
                {photos.map((img, index) => (
                  <button
                    key={index}
                    type="button"
                    onClick={() => ImageViewer.Multi.show({ images: photos, defaultIndex: index })}
                    className="relative h-[72px] w-[72px] overflow-hidden rounded-xl"
                  >
                    <Image src={img} alt="照片" fill unoptimized className="object-cover" />
                  </button>
                ))}
              </div>
            )}
          </div>

          <ApprovalTimeline
            submitter={info.name ? { name: info.name, time: info.createTime } : undefined}
            nodes={exitProcessNodes(info)}
          />

          {approveMode && (
            <div className="rounded-2xl bg-white p-4 shadow-[0_16px_40px_rgba(89,87,87,0.10)]">
              <p className="mb-2 text-[13px] font-semibold text-mid">描述(非必填)</p>
              <div className="rounded-xl border border-border-soft px-3 py-2">
                <TextArea placeholder="请输入内容" value={remark} onChange={setRemark} rows={2} maxLength={50} />
              </div>
            </div>
          )}

          {approveMode && status === 1 && (
            <div className="fixed inset-x-0 bottom-0 flex gap-3 bg-white p-3 shadow-[0_-6px_18px_rgba(89,87,87,0.08)]">
              <button
                type="button"
                disabled={submitting}
                onClick={() => void submit(3)}
                className="flex h-12 flex-1 items-center justify-center rounded-[14px] border border-[#d83b36] text-base font-semibold text-[#d83b36] disabled:opacity-60"
              >
                拒绝
              </button>
              <button
                type="button"
                disabled={submitting}
                onClick={() => void submit(2)}
                className="flex h-12 flex-1 items-center justify-center rounded-[14px] bg-brand text-base font-semibold text-white active:bg-[#d95f00] disabled:opacity-60"
              >
                通过
              </button>
            </div>
          )}
          {approveMode && status === 2 && (
            <div className="fixed inset-x-0 bottom-0 flex gap-3 bg-white p-3 shadow-[0_-6px_18px_rgba(89,87,87,0.08)]">
              <button
                type="button"
                disabled={submitting}
                onClick={() => void submit(5)}
                className="flex h-12 flex-1 items-center justify-center rounded-[14px] border border-[#d83b36] text-base font-semibold text-[#d83b36] disabled:opacity-60"
              >
                拒绝
              </button>
              <button
                type="button"
                disabled={submitting}
                onClick={() => void submit(4)}
                className="flex h-12 flex-1 items-center justify-center rounded-[14px] bg-brand text-base font-semibold text-white active:bg-[#d95f00] disabled:opacity-60"
              >
                保安通过
              </button>
            </div>
          )}
        </div>
      )}
    </PageShell>
  )
}

export default function DormExitApprovalDetailPage() {
  return (
    <Suspense>
      <DormExitApprovalDetailInner />
    </Suspense>
  )
}
